### PR TITLE
npc table localization

### LINKED ISSUE #45: Death Source is not displayed in other locales
Thanks for the addon that makes Enjoying HC more enjoyable.
When using this addon on other locales, the death soruce is not displayed as below. 

death_alert_korean
death_source_korean

Death source after 'by' and 'killed by' is empty. ( ignore characters are "ㅁㅁㅁ",  That's a font problem in Korean, I may make another PR for it later. )
probably because the value is set to `nil` by the table.

### PR DESCRIPTION
**Pull request by jhj0517**
To resolve #45 
I tried to support localization npc table without editing original code at my best.
This PR contains tables for all locales that can be obtained with `GetLocale()`.

- `koKR`(Korean) ✔️
- `frFR` (French) ✔️
- `deDE` (German) ✔️
- `itIT` (Italian) ✔️
- `zhCN` and `zhTW` (Chinese) ✔️
- `ruRU` (Russian) ✔️
- `esES` and `esMX` (Spanish) ✔️
- `ptBR` (Portuguese) ✔️

I've directly confirmed that this PR will correctly display the Death Source in the Korean client.

I've also removed the external `id_to_npc_classic.lua` and `npc_to_id_classic.lua` which are placed in the root project directory to avoid misreference.

All table sizes are the same as `9129`.

### CODE REVIEW

**Comment by aaronma37** [comment]
Wow this is really nice! One concern I had over an approach like this is that each of those giant tables added to the toc will increase load time. Furthermore, the ones copied might be pruned down a bit from the one in the external lib. Thoughts loading them as an external module?

**Comment by jhj0517** [comment]
@aaronma37 I'm not that familiar with addons, but I believe the only way to achieve it is to make them addons and call `LoadAddOn` dynamically.

So I've just made them in [ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables) and updated the localization logic to use it.

[ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables) uses logic to load only needed tables by locale, which will reduce load time for large tables.

I've tested and confirmed that DeathSource is displayed correctly when Deathsource is used with [ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables).

But Deathlog will be dependent on [ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables) and users will download localized table addon for it. 

Would this be a solution?

**Comment by jhj0517** [comment]
@aaronma37 I'm not that familiar with addons, but I believe the only way to achieve it is to make them addons and call `LoadAddOn` dynamically.

So I've just made them in [ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables) and updated the localization logic to use it.

[ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables) uses logic to load only needed tables by locale, which will reduce load time for large tables.

I've tested and confirmed that DeathSource is displayed correctly when Deathsource is used with [ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables).

But Deathlog will depend on [ClassicNPCTables](https://www.curseforge.com/wow/addons/classicnpctables) and users will have to download it along with it.

Would this be a solution?

**Comment by aaronma37** [comment]
Thanks again @jhj0517 ! I merged the other PR you made.  This PR can be closed right?

**Comment by jhj0517** [comment]
@aaronma37 yeah sure. Thanks for merging.

**Pull request closed without merging**
